### ISSUE TITLE
window_equalize function not setting equal observation dates

### ISSUE THREAD

**Issue by wetcircle** [letsgoexploring/fredpy#3]
Using this code I get an `ValueError: object1 and object2 do not have the same observation dates`

```
balance_sheet = fp.series('WALCL')
rrp = fp.series('RRPONTTLD')
tga = fp.series('WTREGEN')
balance_sheet, rrp, tga = fp.window_equalize([balance_sheet, rrp, tga])

balance_sheet.minus(rrp)
```

**Comment by letsgoexploring** [comment]
Hi wetcircle,

The issue is that WALCL and RRPONTTLD have different frequencies. The first
is Weekly, as of Wednesday ('W-WED' in Pandas). The second is Daily ('B' in
Pandas). To combine them in a mathematical expression, you have to resample
one of them; most likely convert RRPONTTLD to W-WED frequency.
fredpy doesn't handle the rich set of frequencies that Pandas allows for.
So I would use fredpy to import the data and then just work with the data
using Pandas methods. Here's an example:

import fredpy as fp
import pandas as pd

# Import data from FRED and store only data (not series metadata)
balance_sheet = fp.series('WALCL').data
rrp = fp.series('RRPONTTLD').data
tga = fp.series('WTREGEN').data

# Reample rrp to Weekly, Wednesday by averaging
rrp = rrp.resample('W-WED').mean()

# Concatenate data into a DataFrame
df = pd.concat([balance_sheet, rrp, tga],axis=1).dropna()
df.columns = ['balance_sheet','rrp','tga']


# Difference
diff = df['balance_sheet'] - df['tga']

print(diff)


Hope this helps.

Brian

**Comment by wetcircle** [comment]
Yes that helps a lot. Thanks for the reply!
